### PR TITLE
L3HotFix

### PR DESCRIPTION
**Pull request by ksiero**

### CODE REVIEW

**Comment by kellekai** [comment]
**The following code has a bug:**
In line 478, u write `bSize` bytes into the file, beginning at address: `FTI_Data[i].ptr`. However, the pointer doesn't get updated. Hence if u write more then 16MB (16777216 Bytes, transfer size), u write the same data again in the file.

**Solution:**
add `char *data_ptr = FTI_Data[i].ptr;` after line 468 and `data_ptr += bSize;` after 489.

https://github.com/leobago/fti/blob/5fc026aa39dc3eae5cfc97bc8e50cca98465b068/src/checkpoint.c#L465-L496

**Comment by leobago** [comment]
@ksiero you did not provide any description for this PR. What is the purpose of it?

**Comment by ksiero** [comment]
This PR fixes L3 RSed writing, the problem were bad variables scopes. I also added fix for output when mpiio fails and added Kai's solution

**Comment by leobago** [comment]
Fix for the L3 bug introduced after the last release.

**Pull request merged**
