### PR TITLE
Checksum

### PR DESCRIPTION
**Pull request by ksiero**
Added checkpoint checksum verification. Checksums are saved in .ftics correspond to .fti checkpoint/ptner/rs files. CMake looks for OPENSSL library. If not found it uses slower more portable md5 algorithm. I had to change condition in diffSizes test to not check sizes of .ftics files.

### CODE REVIEW

**Comment by leobago** [comment]
Thanks for this first draft of the checksum feature. I think it will be really useful for users. One thing we should change is to write the checksum in the metadata files instead of creating another file just for this information. Please check the structure of the metadata files, you will find something like:

[0]
ckpt_file_name                 = Ckpt1-Rank9.fti
ckpt_file_size                 = 4292612
ckpt_file_maxs                 = 4292612

Then I think it will be good to add another line with the checksum, something like:

ckpt_file_checksum        = 131abcfd92034d...

Yes, I also think it will be better to write the checksum in plain text rather than binary.

**Comment by ksiero** [comment]
Your idea is much simpler :) 
Should Ptner and RS files have checksums too?
Should I add option in config file if user want to use checksum verification?

**Comment by leobago** [comment]
I think Checksums should by used always, no need to give the option in the configuration file. Concerning Partner and RS files, I think there is no need to checksum those if the checkpoint files are verified and they are corruption free then that means the Partner and RS files were corruption-free. No need to do the same verification twice. Thus, I think only checking checkpoint files, but in a systematic basis is the way to go.

**Comment by ksiero** [comment]
I already wrote checking Ptner file too, because this is just comparing to different checksum in the file. I think it could be useful. When checkpoint file is corrupted we want to be sure that Ptner file is correct when we do recovery. But if you think it's not needed I can erase that part :)

**Comment by ksiero** [comment]
Leo, you said that you don't know why I changed 2 lines in api.c.
It's because FTI_RecoverFiles returns sum of responds of processes due to "MPI_Allreduce(&fs, &tres, 1, MPI_INT, MPI_SUM, FTI_Exec->globalComm);" This way if there is more than 1 process that returns FTI_NSCS (defined as -1) we get value different that FTI_NSCS (say -4, when 4 process returned FTI_NSCS). That is the reason why I had to change this to res != FTI_SCES. 
Maybe you are right and I should make another pull request with this 2 line changed.

If you will have more doubts please just ask and I will try to explain :)

You did not say anything about my last comment :)

**Comment by kellekai** [comment]
There is a problem when u execute with different checkpoint sizes. When i use 
node_size 4 / group_size 4
head = 0 / keep = 0
mpirun -n 16
and different checkpointzizes, I get after the interrupt, without corrupting anything:
`[FTI Warning 000012] : Checksum do not match. "Local/node3/2017-06-19_17-41-36/l2/Ckpt1-Pcof12.fti" file is corrupted. 77c383dbd8171be3 != 83336c8ed25d9212`
And others.

**Pull request merged**
