### PR TITLE
Compilers

### PR DESCRIPTION
**Pull request by ksiero**
4 configurations on Travis:
1. gcc + openmpi + gfortran
2. clang + openmpi + gfortran
3. icc + impi + ifort 
4. pgcc + openmpi + pgfortran

### CODE REVIEW

**Comment by leobago** [comment]
This pull request removes the Example ready pull request, so that we can easily run the examples. This should be fixed.

**Comment by ksiero** [comment]
Is it ok now?

**Comment by leobago** [comment]
Hi Karol, no it is still not ok. Look at the Pull Request, there are 20 files edited, including source code and tests. There is no reason for this to be. This pull request should ONLY include edits in travis failes and CMake files related to compiling the code. Any other edit  in any other file not related to the compilers has no place in this pull request. Thanks.

**Comment by ksiero** [comment]
Now there are minimal changes to make tests work. I had to remove sudo in tests executions, because with sudo it could not found intel compilers.

**Pull request merged**
