### PR TITLE
Fix for bug #224

### PR DESCRIPTION
**Pull request by rommelsv**
Bug reported on
https://github.com/leobago/fti/issues/224

compile phase tested with

cmake -DNO_OPENSSL:BOOL=TRUE .. &&  make VERBOSE=1
cmake .. && make VERBOSE=1

### CODE REVIEW

**Comment by kellekai** [comment]
Alternatively we can add in the deps/md5 file an MD5() function that implements single call hashing just by calling MD5_init, MD5_update and MD5_final internally. This would make the ifndefs unnecessary. @leobago both solutions should work, its just a matter of style.

**Comment by leobago** [comment]
@rommelsv I think the way proposed by @kellekai is a bit cleaner, could you please implement it that way?

**Comment by leobago** [comment]
@rommelsv, any particular reason why this was closed?

**Comment by rommelsv** [comment]
@leobago, Yep, I'm about to post the other proposal into a different pull request.

**Comment by leobago** [comment]
The other PR has passed all the test and we prefer that solution and it has been merged, so we can close this one. :)

**Pull request closed without merging**
