### PR TITLE
Local recovery routine

### PR DESCRIPTION
**Pull request by nuriallv**
Adding routine to recover just the given variable from the checkpoint file.

### CODE REVIEW

**Comment by ksiero** [comment]
I think you should take variables size from metadata, not from FTI_Data (can be different to the ones in ckpt file):
`offset+=FTI_Data[i].size;`

**Comment by leobago** [comment]
I agree with Karol on this. Karol can you fix it?

**Comment by ksiero** [comment]
Sure

**Comment by nuriallv** [comment]
And, shouldn't the size from the metadata also be the one used in the FTI_Recover() routine?
fread(FTI_Data[i].ptr, 1, FTI_Data[i].size, fd);

**Comment by leobago** [comment]
Good point Nuria. We should change that as well and add some verification before.

**Pull request merged**
