### PR TITLE
Correct the CMake installation process

### LINKED ISSUE #273: CMake install wrong files in wrong place
When using CMake to install to `/usr/local` on centos, I gut the following install (for an example, see the end of  centos_libs Docker image build at https://github.com/pdidev/dockerfiles/runs/495575600?check_suite_focus=true ) :
```
-- Installing: /usr/local/lib/libfti.a
-- Installing: /usr/local/lib/libfti.so
-- Set runtime path of "/usr/local/lib/libfti.so" to ""
-- Installing: /usr/local/include/fti.h
-- Installing: /usr/local/include/fti-intern.h
-- Installing: /usr/local/lib/CMake/FTI/libfti.a
-- Installing: /usr/local/lib/CMake/FTI/libfti.so
-- Set runtime path of "/usr/local/lib/CMake/FTI/libfti.so" to ""
-- Installing: /usr/local/lib/CMake/FTI/FTIConfig.cmake
```

There are multiple things wrong with that:
* on centos, one should install to `/usr/local/lib64` instead of `/usr/local/lib`,
* libraries (`.a`, `.so`) should not be installed in `CMake/FTI`, only CMake stuff goes there,
* `/usr/local/lib/CMake/FTI/FTIConfig.cmake` references a missing `FTILib.cmake`

The result is that on can not use the normal CMake `find_package` to use FTI and that that it is not usable through the default path either.

### PR DESCRIPTION
**Pull request by jbigot**
Fix #273

* Use GNUInstallDirs to install to the correct path
* correctly export the targets to enable CMake to find FTI
* Updated BPP to 1) support python3, 2) not trash the CMake REGISTRY

Ideally, one would like a complete move to "Modern CMake", but this at least fixes the most outstanding issues

### CODE REVIEW

**Comment by kellekai** [comment]
We stopped the checks manually. We are working on a huge pull request and we want to merge this one before all others. We will take care of the merge from your PR into the updated master branch afterwards.

**Comment by kellekai** [comment]
Hi Julien, I get a CMake error when enabling Fortran. The `deps/bpp-v0.3.0/` directory cannot be found. Is it possible that you missed adding this directory to the repository?

**Comment by jbigot** [comment]
It's more than very possible indeed :smile: let me fix that

**Comment by jbigot** [comment]
@kellekai BTW, the version number is now included in the CMakeLists.txt. I put 1.3 for now, not sure what version you want there, but this is useful to support requesting a minimal version from cmake and will have to be updated with every release

**Comment by jbigot** [comment]
In other projects, I parse this version from a dedicated file so as to have it in one single place, but it didn't seem to me you had it anywhere in the current source tree

**Comment by kellekai** [comment]
@jbigot That's a good idea. Maybe we can parse it from the latest release tag... I will look into that. Thanks!

**Comment by jbigot** [comment]
Not sure about the git parsing strategy, this will not work in the release tarball that do not contain the git info...

**Comment by kellekai** [comment]
maybe we can do a pre-commit hook for this. so that the repository always has the correct version. Or we just put a version file and update it every release.
.

**Comment by jbigot** [comment]
sound good indeed

**Pull request merged**
